### ISSUE TITLE
How to evaluate accuracy/Recall@1/MAP@R?

### ISSUE THREAD

**Issue by btseytlin** [KevinMusgrave/pytorch-metric-learning#136]
I would like to evaluate how a method does on a hold-out dataset.

I know about https://github.com/KevinMusgrave/powerful-benchmarker/, but in this case it's too heavy for me - I just want t get a quick indication of whether a method does well. I plan to use powerful benchmarked as a final experiment to obtain benchmarks, but while I am iterating on something its easier to have some quick measure.

I see that the project has some accuracy evaluation using KNN, but I can't understand how it works. Does it run KNN on the embedding space? 

I would like to know how to obtain a retrieval quality score on a test dataset after training. If calculating MAP@R is possible it would be perfect

**Comment by KevinMusgrave** [comment]
Take a look at [AccuracyCalculator](https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/). The general usage is:
```python
from pytorch_metric_learning.utils.accuracy_calculator import AccuracyCalculator

calculator = AccuracyCalculator()

acc_dict = calculator.get_accuracy(query_embeddings,
    reference_embeddings,
    query_labels,
    reference_labels
)
```
```acc_dict``` is a dictionary mapping from metric names to accuracy values
The default metrics are:
- "NMI" (Normalized Mutual Information)
- "AMI" (Adjusted Mutual Information)
- "precision_at_1"
- "r_precision"
- "mean_average_precision_at_r"

NMI and AMI are based on clustering, and the other 3 metrics are based on k-nearest-neighbors search. By default, the calculator sets k to the largest class size in your reference embeddings, so that R-precision and MAP@R can be calculated. (You can also set k yourself when you init the calculator.) However, faiss has an upper limit of 1024 nearest neighbors, so if any of your classes has more than 1024 samples, then for those particular classes, R-precision and MAP@R are really just going to be "precision at 1024" and "MAP@1024". 

The calculator is also fairly easy to extend, so you can add your own metrics. See the documentation for details.

**Comment by btseytlin** [comment]
Awesome, thanks!

'reference_embeddings" are what is usually referred in papers to as "gallery set"?

**Comment by KevinMusgrave** [comment]
Yeah that's the same thing. So for each query embedding, it will find the k most similar embeddings in the reference set. Note that the clustering-based metrics don't use the reference set.
