### ISSUE TITLE
Checking my understanding re: MPerClassSampler / MultiSimilarityMiner

### ISSUE THREAD

**Issue by zabzug-pfpt** [KevinMusgrave/pytorch-metric-learning#189]
Let's say I set `m=8` and `batch_size=32`, and I have eight classes (A-H). That should mean that each batch is comprised of samples from only four classes, and each class is only represented in a single batch. That would then mean that samples from Class A could be in negative pairs with samples from Classes B-D, but never with samples from Classes E-H. Is that all correct?

How then does this interact with the MultiSimilarityMiner? In my first batch, I have eight samples each from Classes A-D. That means that there should be `(32 * 31) / 2 = 496` possible pairs, `4 * ((8 * 7) / 2) = 112` of which should be positive pairs (assuming a sample can't pair with itself). Are there any guarantees about the number of positive or negative pairs that the miner will produce?

**Comment by KevinMusgrave** [comment]
> Let's say I set `m=8` and `batch_size=32`, and I have eight classes (A-H). That should mean that each batch is comprised of samples from only four classes, and each class is only represented in a single batch. That would then mean that samples from Class A could be in negative pairs with samples from Classes B-D, but never with samples from Classes E-H. Is that all correct?

No, it depends on the batch because the labels will keep getting shuffled. For example, something like this will happen:
 - Iteration 1: [A, B, C, D]
 - Iteration 2: [E, F, G, H]
 - Iteration 3: [A, C, E, F]
 - Iteration 4: [B, D, G, H]

> How then does this interact with the MultiSimilarityMiner? In my first batch, I have eight samples each from Classes A-D. That means that there should be `(32 * 31) / 2 = 496` possible pairs, `4 * ((8 * 7) / 2) = 112` of which should be positive pairs (assuming a sample can't pair with itself). Are there any guarantees about the number of positive or negative pairs that the miner will produce?

Your math is correct, other than a minor detail: There will be a total of (32\*31) = 992 pairs because both pairs (x, y) and (y, x) are used. Similarly, there will be (7\*32) = 224 positive pairs. 

The MultiSimilarityMiner provides no guarantees. It's possible for it to return 0 pairs.

FYI, for most batches the MPerClassSampler will return m samples per class, but it's not guaranteed for every batch. So there might occasionally be a batch with say 3 classes, one of which has 16 samples. See [this issue](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/124)

**Comment by zabzug-pfpt** [comment]
> No, it depends on the batch because the labels will keep getting shuffled.

This is dependent on the value of `length_before_new_iter`, though, right? Since there is [only one "reshuffle" per iter in `num_iters`](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/samplers/m_per_class_sampler.py#L30)?

Regarding the MultiSimilarityMiner, is there any way to get telemetry about how many positive / negative miners per batch it returns? That seems like very valuable information to have...

**Comment by KevinMusgrave** [comment]
> This is dependent on the value of `length_before_new_iter`, though, right? Since there is [only one "reshuffle" per iter in `num_iters`](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/samplers/m_per_class_sampler.py#L30)?

I believe it shuffles the labels once it goes through all labels. In your case, if there are total of 8 labels, and you're using 4 labels per batch, then the labels are shuffled every 2 iterations.

> Regarding the MultiSimilarityMiner, is there any way to get telemetry about how many positive / negative miners per batch it returns? That seems like very valuable information to have...

Yes, every tuple miner comes with 3 attributes by default: ```num_pos_pairs```, ```num_neg_pairs```, ```num_triplets```. Since MultiSimilarityMiner is a pair miner, ```num_triplets``` will always be 0. You can access the attributes like this:
```python
hard_pairs = miner(embeddings, labels)
num_pos_pairs = miner.num_pos_pairs
num_neg_pairs = miner.num_neg_pairs
```
