### ISSUE TITLE
MAP calculation issue

### ISSUE THREAD

**Issue by AshishRMenon** [KevinMusgrave/pytorch-metric-learning#217]
I don't understand the need of relevance mask used in the method used to calculate MAP@K 

[https://github.com/KevinMusgrave/pytorch-metric-learning/blob/681682569d282ca4f876920a741f946cac8ca72b/src/pytorch_metric_learning/utils/accuracy_calculator.py#L45](url) 

This matrix seems to be a matrix of ones as per the method used to find it [https://github.com/KevinMusgrave/pytorch-metric-learning/blob/681682569d282ca4f876920a741f946cac8ca72b/src/pytorch_metric_learning/utils/accuracy_calculator.py#L20](url), for small values of K (K less than the count of labels). 

The idea behind MAP@K is to average out the AP's@K  across query samples, where AP is the average of the precisions@k with k =0,1,..K.

**Comment by KevinMusgrave** [comment]
The relevance mask is to make the "R" value correct for each sample. For example, if there are 50 dog images and 30 cat images, then R = 50 for each dog image, but R = 30 for each cat image.

**Comment by AshishRMenon** [comment]
1. So MAP@R is different from MAP? 

2. Could you tell me which is a better metric? If I'm not wrong MAP@R depends on the number of samples of a given class in the query set, while MAP doesn't.

3. Could you help me with some Papers/articles that have used MAP@R instead of MAP

**Comment by KevinMusgrave** [comment]
1. Yes

2. Yes, MAP@R depends on the number of samples of a given class. However, to compute MAP, you have to decide on how many nearest neighbors to retrieve for all of your queries. If you have a clear idea of how many to retrieve then this makes sense. For example, if your application is a search engine, and you want to measure the accuracy of the first 10 search results, then measuring MAP with k = 10 for all your queries makes sense. But in other cases, it isn't clear what value to use for k. For example, if you want to measure the accuracy for some dataset that has 10000 images, it isn't computationally practical to set k = 10000. But it also doesn't make sense to set it to some arbitrary value like k = 50. In this case, MAP@R makes more sense. It sets k for each query so that only a perfectly clustered embedding space gets 100% accuracy.

3. See this paper: https://arxiv.org/abs/2003.08505

**Comment by AshishRMenon** [comment]
Thank You sir.
