### ISSUE TITLE
A potentially wrong sign

### ISSUE THREAD

**Issue by z1w** [KevinMusgrave/pytorch-metric-learning#275]
https://github.com/KevinMusgrave/pytorch-metric-learning/blob/19133d928cdc0aa4d1b49ddf30d5f9c81198649b/src/pytorch_metric_learning/miners/distance_weighted_miner.py#L32

According to the paper https://arxiv.org/pdf/1706.07567.pdf, this should be d-2.0 instead of 2.0-d in the implementation.

**Comment by KevinMusgrave** [comment]
I believe you're referring to the log of this equation:
![image](https://user-images.githubusercontent.com/2314891/107014047-2a124700-6769-11eb-8669-49b89fa9a8b5.png)

But the actually weighting is given by this equation:
![image](https://user-images.githubusercontent.com/2314891/107014121-41513480-6769-11eb-9a0a-bf401a4c5be9.png)

Note that it is using 1/q, so the exponents in the first equation get negated, which is why ```d-2``` becomes ```2-d```

**Comment by z1w** [comment]
Thanks for your prompt reply!
