### ISSUE TITLE
Length of MPerClassSampler

### ISSUE THREAD

**Issue by kazimpal87** [KevinMusgrave/pytorch-metric-learning#28]
Hi,
I'm struggling to make sense of the length function in the MPerClassSampler class:

`def __len__(self):
        return self.list_size`

Wouldn't it make more sense for this function to return `self.length_of_single_pass`?

**Comment by KevinMusgrave** [comment]
The variable names might be a bit confusing, but here is what they mean: 

self.length_of_single_pass = m*num_labels
self.list_size = length of the returned iterable
__len__ should return the length of the returned iterable, so it returns self.list_size. 

For example, if m = 5, and there are 200 labels, then length_of_single_pass = 5*200 = 1000, because it takes 1000 entries to go through all the labels. 

The length of the iterable is 100000 by default, so it will contain 100000 / 1000 passes through all the labels.

**Comment by kazimpal87** [comment]
got it thanks. seeing as how a single pass refers to a single pass through the labels, and not necessarily through the dataset, how do you suggest using these various values to perform an epoch of training?

**Comment by KevinMusgrave** [comment]
MPerClassSampler doesn't have any guarantee of sampling every element in the dataset in a given amount of time, so there isn't a good way to define what an epoch is. I typically just train for some arbitrary number of iterations. 

That said, we could add an option to MPerClassSampler so that when it samples an item from a class, the item is removed from the remaining sample space for that class. When the remaining sample space is depleted, it is refilled. This way it is guaranteed that every dataset item is eventually sampled, though the number of iterations it takes to do that might vary due to randomness, and depending on how unbalanced the dataset is.

**Comment by KevinMusgrave** [comment]
I've posted a relevant explanation [in this other issue](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/39#issuecomment-612233348). It's about the confusing trainer argument, ```iterations_per_epoch```, which is now optional instead of required, in version >= 0.9.82.dev4

**Comment by IWAMOTOHIROYA** [comment]
ありがとうございます

**Comment by Perfumiste777** [comment]
私と横浜F-マリーノ

**Comment by Perfumiste777** [comment]
a good way to define what an epoch is & if passes
a) self.length_of_single_pass?

**Comment by Perfumiste777** [comment]
> a good way to define what an epoch is & if passes MPerClassSampler
> a) self.length_of_single_pass _if = = m*num_labels self.list_size = length of the returned iterable **len** should return the length of the returned iterable, so it returns self.list_size. a1)retuns_MPerClassSampler doesn't have any guarantee of sampling every element in the dataset in a given amount of time, {so m=5 =*200 labels [on multi mode scaling totally when on *],m=5 } a2) returns_,[MPerClassSampler bataset {must be balanced so samples
> =m=5*,,200 = result} ....will be update shortly(20-04-&02:$3)..&if % =
> 
> 私と横浜F-マリーノTime not element until sample rebrowse guarante.
