### ISSUE TITLE
Definition of precision@K and recall@K

### ISSUE THREAD

**Issue by whynotw** [KevinMusgrave/pytorch-metric-learning#283]
Hi,

I am confused about the definitions of Recall@K and Precision@K.

In this implementation, **precision_at_k** is 100% only if **curr_knn_labels** and **gt_labels** are exactly the same (all k elements are correct). But in the paper _A Metric Learning Reality Check_, a statement is as follows: "Note that 100% Recall@1 means that Recall@K for any K>1 is also 100%." It points out that only one of k nearest elements of **curr_knn_labels** matching **gt_labels** is enough. Are these two matching rules consistent?

Another statement is that "Precision@1 also known as Recall@1 in the previous sections and in metric learning papers." Is Precision@1 equal to Recall@1?

Am I misunderstanding that? Many thanks.

**Comment by KevinMusgrave** [comment]
The "Recall@K" term used in metric learning papers is very confusing. I'll try to clarify here. 

## "Recall@K" in metric learning papers
This is computed as follows:
For each sample in the dataset:
- Get the K nearest neighbors
- If at least 1 of those nearest neighbors is a match, then the sample gets a score of 1. Otherwise it scores 0.

So in metric learning papers, Recall@1  means "is the 1st nearest neighbor correct?"

## Recall@K and Precision@K in other contexts (e.g. information retrieval)
Precision is the [fraction of retrieved documents that are relevant](https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-unranked-retrieval-sets-1.html).

Recall is the [fraction of relevant documents that are retrieved](https://nlp.stanford.edu/IR-book/html/htmledition/evaluation-of-unranked-retrieval-sets-1.html).

## Comparing the two
Let MetricRecall@K be the metric learning version of "Recall@K". Then:

- Precision@1 is equivalent to MetricRecall@1
- Precision@K is different from MetricRecall@K for K > 1
- Recall@K is different from MetricRecall@K for all K, unless the number of relevant samples in the dataset is 1

In this library, there is no MetricRecall@K. There is only Precision@K, which happens to be equivalent to MetricRecall@K when K == 1

**Comment by whynotw** [comment]
Thanks for clear explanation!

BTW, there is no implementation for "MetricRecall@K" in accuracy calculator, right?
