### ISSUE TITLE
mAP validity

### ISSUE THREAD

**Issue by VChristlein** [KevinMusgrave/pytorch-metric-learning#290]
Hi, thank you for this great library! I was just testing your AccuracyCalculator(). However, it seems that mAP results in a totally different value than expected. I implemented it in a very basic way and compared it with your output, s. https://gist.github.com/VChristlein/fd55016f8d1b38e95011a025cbff9ccc

Do I call your function in a wrong way or do I miss something?

**Comment by KevinMusgrave** [comment]
Thanks for testing this. I'll try to figure out what's wrong

**Comment by KevinMusgrave** [comment]
The discrepancy is caused by the k value used in the k-nn search.

There are 2 ways to eliminate the discrepancy:

## 1. Set the k value when you initialize AccuracyCalculator
```python
acc = accuracy_calculator.AccuracyCalculator(k=len(encs)-1)
```
Now the values should match your implementation.


## 2. Change your implementation to compute k "automatically". 

Leave AccuracyCalculator as is:
```python
acc = accuracy_calculator.AccuracyCalculator()
```
and instead, make some modifications to your evaluate function.

In AccuracyCalculator, if k is not specified, it is set as follows:
 - Count the number of occurrences for each label. Set k to the maximum number of occurrences. For example, if the labels are [0, 0, 1, 1, 1, 1, 1], then k will be set to 5.
 - After that, set k to min(1023, k), because faiss has a limit on the value of k (1024 for older versions of cuda, and 2048 for newer versions of cuda). It's set to 1023 instead of 1024 to allow for same-source embeddings, i.e. it will search for 1023+1 == 1024.

Here is your ```evaluate``` function modified. I added ```##### START DIFF #####``` and ```##### END DIFF #####``` to indicate where I made changes.
```python
def evaluate(encs, labels):
    """
    evaluate encodings assuming using associated labels
    parameters:
        encs: TxD encoding matrix
        labels: array/list of T labels
    """

    ##### START DIFF #####
    max_k = int(max(np.bincount(labels)))
    indices, _ = get_knn(encs, encs, max_k, True)
    all_indices, _ = get_knn(encs, encs, len(encs)-1, True)
    ##### END DIFF #####

    # let's use the most simple mAP implementation
    # of course this can be computed much faster using cumsum, etc.
    n_encs = len(encs)
    mAP = []
    mAP_at_r = []
    correct = 0
    for r in range(n_encs):
        precisions = []
        rel = 0
        # indices doesn't contain the query index itself anymore, so no correction w. -1 necessary
        ##### START DIFF #####
        all_rel = np.count_nonzero(labels[all_indices[r]] == labels[r])
        prec_at_r = []
        for k in range(max_k):
        ##### END DIFF #####
            if labels[ indices[r,k] ] == labels[ r ]:
                rel += 1
                precisions.append( rel / float(k+1) )
                if k == 0:
                    correct += 1

                #mAP@R
                if k < all_rel:
                    prec_at_r.append( rel / float(k+1) )

        ##### START DIFF #####
        avg_precision = np.mean(precisions) if len(precisions) > 0 else 0
        mAP.append(avg_precision)
        #mAP@R
        avg_prec_at_r = np.sum(prec_at_r) / all_rel if all_rel > 0 else 0
        mAP_at_r.append(avg_prec_at_r)
        ##### END DIFF #####

    mAP = np.mean(mAP)
    mAP_at_r = np.mean(mAP_at_r)
    print('precision@1: {} - mAP: {} - mAP@R: {}'.format(float(correct) /
                                                          n_encs, mAP, mAP_at_r))
```


## The documentation should be improved

The behavior of setting k isn't documented (it just says ["the value of k will be determined automatically"](https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/#parameters)), so that is something I should fix

**Comment by KevinMusgrave** [comment]
I added an explanation to the documentation: https://kevinmusgrave.github.io/pytorch-metric-learning/accuracy_calculation/

**Comment by VChristlein** [comment]
Thank you for figuring out what is wrong in such a fast way!

I must admit that I am not very happy with your solution: 
- what happens if I have too many features/embeddings, i.e. more than 1023? Any larger identification/retrieval dataset couldn't be used - at least not mAP, mAP@R would probably still work fine since it's quite unlikely that you have more than 1023 relevants per class. 
- setting the default k value by using bincount also has another disadvantage: what happens if a relevant comes after the max_k value, e.g. [0, 0, 1, 1, 1, 1, 1] -> max_k = 5, but given this list, 2 more samples would not be used to compute mAP -> wrong mAP result

Possible solution: 
1. removing the bincount way of limiting the maximum k value
2. fix your get_knn() function by changing:
`if faiss.get_num_gpus() > 0:`
to 
`if faiss.get_num_gpus() > 0 and k < 1024:` 
In this way, for larger k, the CPU version of faiss without this limitation would be called.

**Comment by KevinMusgrave** [comment]
> Possible solution:
> 
> 1. removing the bincount way of limiting the maximum k value
> 2. fix your get_knn() function by changing:
>    `if faiss.get_num_gpus() > 0:`
>    to
>    `if faiss.get_num_gpus() > 0 and k < 1024:`
>    In this way, for larger k, the CPU version of faiss without this limitation would be called.

This makes sense, good idea. So this would be the default behavior (```k=None```), and then I could include a special mode like ```k="max_bin_count"``` to allow for the bincount way of selecting k.

**Comment by KevinMusgrave** [comment]
The new behavior is in v0.9.98. 

I added your script as a [unit test](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/tests/utils/test_calculate_accuracies_large_k.py)

The documentation will be updated as well.
