### ISSUE TITLE
Default LP.get_hook_container() primary_metric disagreement with AccuracyCalculator

### ISSUE THREAD

**Issue by wconnell** [KevinMusgrave/pytorch-metric-learning#52]
If  "mean_average_precision_at_r" is excluded in your `AccuracyCalculator` object you will run into an evaluation error if you have instantiated hooks with `hooks = LP.get_hook_container(record_keeper)`. Maybe you should be able to pass your `AccuracyCalculator` to this function?

**Comment by KevinMusgrave** [comment]
One of the arguments for HookContainer is ```primary_metric```. If the user excludes a metric from AccuracyCalculator, then I think it should be up to them to change the primary metric to a non-default value. However, I see that ```get_hook_container``` doesn't accept any arguments other than ```record_keeper``` so that should probably be changed to ```**kwargs``` and then pass that to initialize HookContainer.

Actually, do you mean we should move the ```primary_metric``` argument to AccuracyCalculator, and then HookContainer reads from that?

**Comment by wconnell** [comment]
> Actually, do you mean we should move the primary_metric argument to AccuracyCalculator, and then HookContainer reads from that?

That was my initial impulse after noticing the limits of `get_hook_container`. Since `tester` already includes an argument for the `AccuracyCalculator` class. It makes sense to me to keep the accuracy-related params in the same class. Sorry wasn't clear earlier.

**Comment by KevinMusgrave** [comment]
In v0.9.84.dev0 you can do ```get_hook_container(record_keeper, primary_metric="AMI")``` and it should work. I'm not sure about moving ```primary_metric``` to AccuracyCalculator because it will be unused in AccuracyCalculator. I view ```primary_metric``` as mainly a logging and training hook issue (for determining when accuracy has plateaued).

**Comment by KevinMusgrave** [comment]
This is now in v0.9.84
