### ISSUE TITLE
self-defined triplet

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#596]
Hi,

I want to form my own triplet from the dataset

I have 2 classes (`1` & `0`) and my anchor is always from `1`

1. what should i return in my dataset object's getitem function
2. Should I use two-stream trainer? (and what does the `label` mean in the document?)
3. do i have to pass a miner or just leave it empty dictonary?

I've checked two-stream trainer. It seems that it will form triplets with anchor from class `1` or class `2` but I only want the anchor from class `1`

Thank you

**Comment by KevinMusgrave** [comment]
The docs for `TwoStreamMetricLoss` are not very clear. Basically it expects that each `(anchor, posneg)` share the same `label`. For this reason, if you want all anchors to come from class 1, then `TwoStreamMetricLoss` probably won't work because the entire batch will have to be of class 1.

If you're already using `MetricLossOnly`, maybe the easiest approach is to extend it:

```python
from pytorch_metric_learning.trainers import MetricLossOnly
from pytorch_metric_learning.utils import loss_and_miner_utils as lmu


class OneClassAnchors(MetricLossOnly):
    def calculate_loss(self, curr_batch):
        data, labels = curr_batch
        embeddings = self.compute_embeddings(data)
        mask, indices_tuple = self.triplets_with_anchors_from_class1_only(labels)
        self.losses["metric_loss"] = self.loss_funcs["metric_loss"](
            embeddings[mask], indices_tuple=indices_tuple, ref_emb=embeddings[~mask]
        )

    def triplets_with_anchors_from_class1_only(self, labels):
        mask = labels == 1
        indices_tuple = lmu.get_all_triplets_indices(labels[mask], labels[~mask])
        return mask, indices_tuples
```

**Comment by brianw0924** [comment]
Thank you for the reply!!! It really helps
