### ISSUE TITLE
NT-Xet loss?

### ISSUE THREAD

**Issue by JohnGiorgi** [KevinMusgrave/pytorch-metric-learning#6]
I am just wondering if there is anything similar to the normalized temperature-scaled cross-entropy loss (referred to as NT-Xent in [SimCLR](https://arxiv.org/abs/2002.05709), Eq. 1) implemented in this library?

If not, might I make a request for this? 😄

**Comment by KevinMusgrave** [comment]
Thanks for the suggestion. At first glance it looked easy to implement, but vectorizing it was trickier than I expected. 

Anyway, the latest version (0.9.73) has NTXentLoss. Here is some [short documentation](https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#ntxentloss) + [the actual implementation](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/pytorch_metric_learning/losses/ntxent_loss.py).

In the SimCLR paper, I think the assumption is that each sample in the batch belongs to just 1 positive pair. Therefore, for each positive pair (X, Y), the denominator in the loss consists of all other possible pairs that contain X, and they are all negative pairs.

For this library, I want to assume that each sample can belong to many positive pairs. So I think the logical extension is that for each positive pair (X, Y), the denominator contains only the negative pairs that contain X. If each sample belongs to only 1 positive pair, this will be equivalent to the SimCLR loss.

Also, like the other loss functions, this forward function has an optional third argument for hard pairs/triplets (as output by a miner). In this case, every numerator will contain a hard pair (X, Y), and the denominator will have hard negatives that contain X.

**Comment by KevinMusgrave** [comment]
I think I can get rid of the torch.exp() for computing the numerator, and move the numerator outside of the torch.log

**Comment by JohnGiorgi** [comment]
Wow, great, that was very fast!

Just to make sure I understand...

If I have two tensors: `anchor_embeddings` and `positive_embeddings` and I want to use them with this loss function in the same way as SimCLR, I might:

```python
embeddings = torch.cat((anchor_embeddings, positive_embeddings))
indices = torch.arange(0, anchor_embeddings.size(0), device=anchor_embeddings.device)
labels = torch.cat((indices, indices))

loss = NTXentLoss(temperature=0.10)
loss(embeddings, labels)
```

Which would assign every positive pair the same integer label. Is my thinking correct here?

**Comment by KevinMusgrave** [comment]
Yep that looks correct to me

**Comment by JohnGiorgi** [comment]
@KevinMusgrave Awesome. Thanks for the sanity check

**Comment by CSerxy** [comment]
> Yep that looks correct to me

Hi Kevin, when I launched the same code of John's, I got a error indicating "RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'other' in call to _th_max" 

Do you know why this would happen? Many thanks!

**Comment by CSerxy** [comment]
> Wow, great, that was very fast!
> 
> Just to make sure I understand...
> 
> If I have two tensors: `anchor_embeddings` and `positive_embeddings` where the rows correspond to positive pairs, and I want to use them with this loss function in the same way as [SimCLR](https://arxiv.org/abs/2002.05709), I might:
> 
> ```python
> import torch
> from pytorch_metric_learning.losses import NTXentLoss
> 
> batch_size = 16
> embedding_dim = 512
> 
> # Just to make this example runnable
> anchor_embeddings = torch.randn(batch_size, embedding_dim)
> positive_embeddings = torch.randn(batch_size, embedding_dim)
> 
> embeddings = torch.cat((anchor_embeddings, positive_embeddings))
> indices = torch.arange(0, anchor_embeddings.size(0), device=anchor_embeddings.device)
> labels = torch.cat((indices, indices))
> 
> loss = NTXentLoss(temperature=0.10)
> loss(embeddings, labels)
> ```
> 
> Which would assign every positive pair the same integer label. Is my thinking correct here?

Hi John, thanks for your example codes. I wonder if you launched it and did you meet some errors such as "RuntimeError: Expected object of scalar type Half but got scalar type Float for argument #2 'other' in call to _th_max"?

If so, how did you solve this? Many thanks!

**Comment by KevinMusgrave** [comment]
@CSerxy This is caused by calls to .float() in the NTXentLoss function. See https://github.com/JohnGiorgi/DeCLUTR/issues/60 for a discussion about it. I've made [an issue](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/121) to fix this problem, so it's definitely on my to-do list.

**Comment by CSerxy** [comment]
> @CSerxy This is caused by calls to float() in the NTXentLoss function. See [JohnGiorgi/DeCLUTR#60](https://github.com/JohnGiorgi/DeCLUTR/issues/60) for a discussion about it. I've made [an issue](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/121) to fix this problem, so it's definitely on my to-do list.
> 
> Currently, the only way around it is to download the source code for NTXentLoss, and [cast one of the tensors](https://github.com/JohnGiorgi/DeCLUTR/issues/60#issuecomment-608966647) to half().
> 
> The code for the loss function is [here](https://github.com/KevinMusgrave/pytorch-metric-learning/blob/master/src/pytorch_metric_learning/losses/ntxent_loss.py).
> 
> Here's a version you can copy/paste into your own code. It should work with half-precision.
> 
> ```python
> import torch
> from pytorch_metric_learning.losses import GenericPairLoss
> 
> class NTXentLoss(GenericPairLoss):
> 
>     def __init__(self, temperature, **kwargs):
>         super().__init__(use_similarity=True, mat_based_loss=False, **kwargs)
>         self.temperature = temperature
> 
>     def _compute_loss(self, pos_pairs, neg_pairs, indices_tuple):
>         a1, p, a2, _ = indices_tuple
> 
>         if len(a1) > 0 and len(a2) > 0:
>             pos_pairs = pos_pairs.unsqueeze(1) / self.temperature
>             neg_pairs = neg_pairs / self.temperature
>             n_per_p = (a2.unsqueeze(0) == a1.unsqueeze(1)).float()
>             neg_pairs = neg_pairs*n_per_p
>             neg_pairs[n_per_p==0] = float('-inf')
> 
>             max_val = torch.max(pos_pairs, torch.max(neg_pairs, dim=1, keepdim=True)[0].half()) ###This is the line change
>             numerator = torch.exp(pos_pairs - max_val).squeeze(1)
>             denominator = torch.sum(torch.exp(neg_pairs - max_val), dim=1) + numerator
>             log_exp = torch.log((numerator/denominator) + 1e-20)
>             return {"loss": {"losses": -log_exp, "indices": (a1, p), "reduction_type": "pos_pair"}}
>         return self.zero_losses()
> ```

Thank you so much, Kevin! Yeah, I solved this problem by getting rid of fp16 in training. 

However, I met another error telling me "AttributeError: 'NTXentLoss' object has no attribute 'backward'". Is it because in this package, the backward hasn't been implemented?

Have a nice weekend!

**Comment by KevinMusgrave** [comment]
@CSerxy Calling .backward() should work. I think you might be calling .backward() on the loss function rather than the loss value.

**Comment by HelloWorldLTY** [comment]
Hi, I intend to use InfoNCE loss in a graph, but I am confused about the definition of SimCLR. Based on the random sample approach mentioned in this paper, is it reasonable to choose only one pair in the dataset as positive pair while the rest of pairs are treated as negative pairs? What if all the pairs we sampled are actually positive or negative pairs? Thanks a lot.

**Comment by KevinMusgrave** [comment]
@HelloWorldLTY Any number of positives and negatives is fine, just as long as the batch contains both positives and negatives.

> What if all the pairs we sampled are actually positive or negative pairs?

Then the loss computation will be skipped and it will return 0.

**Comment by HelloWorldLTY** [comment]
Hi, but according to the previous discussion, they choose to assign same labels to all the samples, is it correct? Is it possible for me to access more examples? Thanks

**Comment by KevinMusgrave** [comment]
Positive pairs are formed by samples with the same label. Here are some examples:

```python
# 0 positive pairs because no two samples have the same label
labels = [0, 1, 2, 3, 4, 5]

# 0 negative pairs because all the samples have the same label
labels = [0, 0, 0, 0, 0]

# 1 positive pair and 6 negative pairs
# (Technically, there are 2 positive pairs and 12 negative pairs because this library counts (x,y) and (y,x) as two separate pairs)
labels = [0, 0, 1, 2, 3]
```

**Comment by HelloWorldLTY** [comment]
It makes sense. Thanks a lot!

**Comment by KevinMusgrave** [comment]
`SelfSupervisedLoss` has been added to v2.0.0. If you have two "views" of data, you don't need to make labels anymore:

```python
from pytorch_metric_learning.losses import SelfSupervisedLoss
loss_func = SelfSupervisedLoss(NTXentLoss())
embeddings = model(data)
augmented = model(augmented_data)
loss = loss_func(embeddings, augmented)
```

**Comment by HelloWorldLTY** [comment]
Many thanks for your update! I will try it now and see if it still needs much memory.

**Comment by HelloWorldLTY** [comment]
Hi, I find that this loss function will generally occupy large gpu memory, for example, for the data list with emb1 500*32 emb2 400*32, the memory usage is larger than 3 GB. Is it normal? Are there any other memory efficiency implement for this loss? Thanks a lot.

**Comment by KevinMusgrave** [comment]
If you don't have a `ref_emb` then you can try this batching code: https://github.com/KevinMusgrave/pytorch-metric-learning/issues/547#issuecomment-1304907510

In your case, it looks like you're using a `ref_emb` because you mentioned `emb1` and `emb2`,  so the batching code becomes a bit simpler:

```python
import torch
from pytorch_metric_learning import losses, reducers
from pytorch_metric_learning.utils import loss_and_miner_utils as lmu

# setup
device = torch.device("cuda")
batch_size = 1200
emb = torch.randn(batch_size, 32, device=device)
ref_emb = torch.randn(batch_size, 32, device=device)
labels = torch.randint(0, 10, size=(batch_size,), device=device)
ref_labels = torch.randint(0, 10, size=(batch_size,), device=device)


loss_fn2 = losses.NTXentLoss(reducer=reducers.DoNothingReducer())
# Do the following for each batch
loss = 0
sub_batch_size = 32
e = sub_batch_size
all_losses = []
for s in range(0, batch_size, sub_batch_size):
    # get current anchors
    curr_emb = emb[s:e]
    curr_labels = labels[s:e]

    # compute loss
    curr_loss = loss_fn2(curr_emb, curr_labels, ref_emb=ref_emb, ref_labels=ref_labels)
    all_losses.append(curr_loss["loss"]["losses"])
    s = e
    e += sub_batch_size

all_losses = torch.cat(all_losses, dim=0)
loss = torch.mean(all_losses)
print(loss)
```

The code is also available in this colab notebook: https://colab.research.google.com/drive/1pL1LeK50VAbgy1YxHH0LnN9WkOxhtKXk?usp=sharing

I should probably add this batching code to the library, as a utility function.

**Comment by HelloWorldLTY** [comment]
Hi, so this approach can help us reduce memory usage, it it correct? But how to choose a suitable sub_batch_size, actually I am not sure about it. And in my case, ref_emb and emb may not have the same length. Thanks.

**Comment by KevinMusgrave** [comment]
Yes it'll reduce memory usage and the loss will be equal to the non-batched version.

You should make `sub_batch_size` as large as possible (whatever fits in memory).

The batching code does not require `emb` and `ref_emb` to have the same length.

(SelfSupervisedLoss _does_ require `emb` and `ref_emb` to have the same length, but the batching code uses `NTXentLoss` directly, instead of the `SelfSupervisedLoss` wrapper.)

**Comment by HelloWorldLTY** [comment]
Thanks, I think I can use the wrapper and mofity the batch code to fit my requirement. Thanks a lot.

**Comment by stompsjo** [comment]
Hello and happy St. Patrick's Day! In the spirit of keeping this thread alive, I was hoping to submit my own clarification question on `NTXent` loss. I am only trying to recreate the loss function from the original SimCLR paper. So, am I correct in understanding that given two "views" of the data (`augmented1` and `augmented2`), I can use `SelfSupervisedLoss(NTXentLost())(augmented1, augmented2)` to get a loss scalar?

I am mainly trying to understand the idea of positive pairs versus negative examples given a minibatch as written in SimCLR. If my read of your source code is correct, the same behavior is incorporated in this loss function. (i.e. "Instead, given a positive pair, similar to (Chen et al. 2017), we treat the other 2(N-1) augmented examples within a minibatch as negative examples." from SimCLR)

**Comment by KevinMusgrave** [comment]
> So, am I correct in understanding that given two "views" of the data (`augmented1` and `augmented2`), I can use `SelfSupervisedLoss(NTXentLost())(augmented1, augmented2)` to get a loss scalar?

That's correct.

> I am mainly trying to understand the idea of positive pairs versus negative examples given a minibatch as written in SimCLR. If my read of your source code is correct, the same behavior is incorporated in this loss function. (i.e. "Instead, given a positive pair, similar to (Chen et al. 2017), we treat the other 2(N-1) augmented examples within a minibatch as negative examples." from SimCLR)

Yes, specifically: `augmented1[0]` will form a positive pair with `augmented2[0]`, and it will form negative pairs with `augmented[i]` for i in `[1, batch_size]`

**Comment by KevinMusgrave** [comment]
@stompsjo Don't forget to call `optimizer.zero_grad()` before `loss.backward()`

**Comment by dhruvbird** [comment]
@KevinMusgrave I wanted to understand this sentence better in the context of the NT-Xent loss.

> For this library, I want to assume that each sample can belong to many positive pairs. So I think the logical extension is that for each positive pair (X, Y), the denominator contains only the negative pairs that contain X, plus (X, Y).

My understanding (which could be incomplete) is that this is a form of cross entropy loss, and hence, won't work for multi-label settings. i.e. if we expect more than exactly 1 positive pair, then you'd need to model each pair's similarity as a BCELoss formulation. i.e. Then you'd probably apply sigmoid on each individual similarity value and see how close it is to 1.0 or 0.0 - except that naively this wouldn't work either since Cosine Similarity produces results in the range -1.0 to +1.0.

For example, if out of 4 pairs, 3 of them are positive, then this is what we get with softmax.

```
>>> x = torch.tensor([0.1, 0.9, 0.9, 0.9])
>>> x.softmax(dim=0)
tensor([0.1303, 0.2899, 0.2899, 0.2899])
```

which is far from the 1.0 we expect for the 3 positive pairs.

Maybe sigmoid with temperature is the solution here (just thinking out aloud).

```
>>> x = torch.tensor([0.1, 0.9, 0.9, 0.9])
>>> x.sigmoid(), (x / 0.5).sigmoid(), (x / 0.05).sigmoid()
(tensor([0.5250, 0.7109, 0.7109, 0.7109]),
 tensor([0.5498, 0.8581, 0.8581, 0.8581]),
 tensor([0.8808, 1.0000, 1.0000, 1.0000]))
```

And then use BCELoss on the result.

Thoughts?

**Comment by aaaaarrp** [comment]
> `SelfSupervisedLoss` has been added to v2.0.0. If you have two "views" of data, you don't need to make labels anymore

Sorry I am new to this. I am trying to implement the simCLR v1 paper.
So according to this - if i just pass the two embeddings of two augmented views from of image, it will give me a loss right ?
```python
from pytorch_metric_learning.losses import SelfSupervisedLoss
loss_func = SelfSupervisedLoss(NTXentLoss())
...
for (augmented_view_1, augmented_view_2), _  in train_loader):
      embedding1, embedding2 = model(augmented_view1, augmented_view2)
      loss = loss_func(embedding1, embedding2)
      self.optimizer.zero_grad()
      loss.backward()
      self.optimizer.step()
...
```

**Comment by stompsjo** [comment]
> So according to this - if i just pass the two embeddings of two augmented views from of image, it will give me a loss right ?

@aaaaarrp I'm certainly not Kevin, but your use of the loss function looks great to me!

Depending on the size of your embeddings, you may still run into memory usage issues using `SelfSupervisedLoss(NTXentLoss())`. If so, you would need to do the sub-batching I described above. A follow-up question for others (cc @KevinMusgrave), is this still a concern with the v2.0.0 updates to `SelfSupervisedLoss`? i.e. Does `symmetric=True` also reduce memory issues?

**Comment by stompsjo** [comment]
> My understanding (which could be incomplete) is that this is a form of cross entropy loss, and hence, won't work for multi-label settings. i.e. if we expect more than exactly 1 positive pair, then you'd need to model each pair's similarity as a BCELoss formulation.

@dhruvbird I know this question wasn't directed at me, but could you elaborate on why cross-entropy loss would not work for multi-labeled settings? Given the equation for `NTXentLoss`, it seems to me there is nothing preventing multi-labeled use _if_ some level of reference labels are provided, [this comment](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/600#issuecomment-1483894037) as an example.

**Comment by dhruvbird** [comment]
> > My understanding (which could be incomplete) is that this is a form of cross entropy loss, and hence, won't work for multi-label settings. i.e. if we expect more than exactly 1 positive pair, then you'd need to model each pair's similarity as a BCELoss formulation.
> 
> @dhruvbird I know this question wasn't directed at me, but could you elaborate on why cross-entropy loss would not work for multi-labeled settings? Given the equation for `NTXentLoss`, it seems to me there is nothing preventing multi-labeled use _if_ some level of reference labels are provided, [this comment](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/600#issuecomment-1483894037) and [this comment](https://github.com/KevinMusgrave/pytorch-metric-learning/discussions/606#discussioncomment-5542877) as examples.

@stompsjo Here's what I'm thinking - Cross Entropy Loss (CEL) will apply a positive label to all the "correct" values during classification. Assume that each mini-batch of SimCLR has 10 images as input, 5 original, and 5 augmented versions of the 5 original images. Hence, we have 9 pairs that we want to classify. In the usual case, we have 1 pair that is positive and 9-1=8 pairs that are negative (9 pairs overall since we ignore the similarity of an image with itself), for each of the "outputs" after all-pairs cosine similarity. Hence, CEL is perfect for this.

In the multi-label case, there are 2 sub-cases:

1. Each row in every mini-batch has the same number of positive and negative pairs. For example, if your mini-batch has 15 images, and we have 5 original images, but 2 (and not 1) augmented version of each of the 5 original images, we have 14 pairs, where for each "output" from all-pairs cosine-similarity, 2 pairs are positive, and 12 pairs are negative. In this case, CEL will assign a probability of 0.5 to each of the correct pairs, and the loss will effectively be distributed equally across both positive pairs.
2. This become more interesting in case each image has an different number of augmented images provided. For example, if you have 2 original images (A and B), and we create 2 copies of the 1st image (A) and 4 copies of the 2nd image (B). This gives us a total of 2 + 2 + 4 = 8 images. For each image and augmented image originating from A, we have 2 positive pairs, and for each image and augmented image originating from B, we have 4 positive pairs. This means that the labeled probability (ground truth probability) for CEL would have to be 0.5 for A images and 0.25 for B images. This weights the positive pairs differently depending on how many augmented versions of an image exist in the unbalanced case. This is the case I'm more worried above since it will will cause the model to learn differently based on how many augmentations of an image were fed into the model.

The key point I'm hinging this whole discussion on is that when using probabilities with CEL instead of class labels, the probability values must all add up to 1.0

I hope this helps explain what I am thinking. Please let me know if you spot any gaps in my understanding.

**Comment by KevinMusgrave** [comment]
@aaaaarrp
> Sorry I am new to this. I am trying to implement the simCLR v1 paper. So according to this - if i just pass the two embeddings from two augmented views of an image, it will give me a loss right ?

Yes your usage is correct.

@stompsjo 
> is this still a concern with the v2.0.0 updates to SelfSupervisedLoss? i.e. Does symmetric=True also reduce memory issues?

Right now SelfSupervisedLoss is just a really simple wrapper that [makes some assumptions](https://github.com/KevinMusgrave/pytorch-metric-learning/discussions/632#discussioncomment-6023324). It doesn't do anything to reduce memory. It just gets rid of some boilerplate code.

@dhruvbird 
I agree with @stompsjo's reply.

**Comment by dhruvbird** [comment]
@stompsjo Thanks for providing links to earlier discussions! I'll provide my replies inline.

> @dhruvbird Thank you for the explanation! I certainly agree with you that CEL applied to classification would expect some ground truth probabilities to add up to zero. And for a set of 5 original and 5 augmented images, there would be 9 total pairs, one of which is positive if we assume all five are different.
> 
> However, `NTXentLoss` is not used for classification, at least not in the was SimCLR uses it. `NTXentLoss` is applied to representations of input data (e.g. images) and penalizes difference in the representations for positives pairs and encourages differences in representations for negative pairs. In that sense, the output of `NTXentLoss` is not necessarily a class probability in the same way as for CEL. Also, because of the log of the sum of exponentials in the denominator, `NTXentLoss` itself does not necessarily range between 0 and 1.

I'm looking at this formula for https://paperswithcode.com/method/nt-xent which resembles CEL applied on each row of the output. Each row of the output corresponds to a single input image compared with every other image in the same mini-batch. This "expansion" is a result of applying cosine similarity with every other image in the mini-batch. Hence, we can consider this to be a multi-class classification problem where you're trying to classify each "pair" as belonging to a "similar" class or some other class. The way this is formulated is that we assume there to be `N - 1` classes (for a mini-batch with N samples, we have `N` rows and `N-1` columns in the output matrix of cosine similarity), with exactly 1 class being the "similar pair" class, and the rest semantically standing for some abstract notion of distinct dis-similar classes. Since the dis-similar pairs don't contribute to the loss directly, it doesn't matter what they stand for in practice.

The way I framed it suggests that you can't have more than one positive pair per row if you're using hard labels. If you did, then it would be a multi-label classification problem or a problem where you have soft ground truth probabilities, with each pair distributing the probabilities equally in that row.

> 
> The labels passed to `NTXentLoss` need not be true labels, but simply indicate which embeddings are positive (this is how the `indices_tuple` is created).

Yes, this is consistent with my understanding as well.

> AFAIK, the loss function will then create one loss term for each positive pair (so in the event that there are 2 positive pairs in a set, two loss terms will be created because `NTXentLoss` is computed for every positive pair applied to the numerator). [This comment](https://github.com/KevinMusgrave/pytorch-metric-learning/issues/179#issuecomment-1503822592) does a great job of illustrating the functionality.
> 
> Does that make sense? Let me know if I have made an error anywhere.

Thanks for linking to the comment - I'll copy the main parts inline below for ease of reading.

> Say we have a batch size of 4 with labels: [dog, dog, cat, mouse].
> In this case there will be two losses:

> one loss for the positive pair [0,1] with negative pairs [0,2], [0,3].
> one loss for the positive pair [1,0] with negative pairs [1,2], [1,3].
> So the negative pair [2,3] (cat, mouse) isn't used at all.

While this is accurate (i.e. there is a single loss for each positive pair), it doesn't generalize to the cases where there are multiple positive pairs associated with a single sample. For example,

Suppose we have a batch of size 5 with labels [dog, dog, dog, cat, mouse]
In this case there will still be 2 losses (and not 4 losses):

one loss for the positive pair(s) [0, 1] and [0, 2]
one loss for the positive pair(s) [1, 0] and [1, 2]

And these losses will have to be be scaled to 0.5 per pair for the row-wise labels to sum up to 1.0 since this is CEL at the end of the day. CEL is derived from KL divergence which is a measure of the difference between 2 probability distributions.

I hope this help convey how I'm thinking about this problem and would love to hear if you agree with the framing above regarding there still being 2 loss terms.

**Comment by KevinMusgrave** [comment]
> one loss for the positive pair(s) [0, 1] and [0, 2]
one loss for the positive pair(s) [1, 0] and [1, 2]

In this library, there will be 4 loss terms, one for each positive pair:
- [0, 1]
- [0, 2]
- [1, 0]
- [1, 2]

**Comment by dhruvbird** [comment]
> In this library, there will be 4 loss terms, one for each positive pair:
> 
> * [0, 1]
> * [0, 2]
> * [1, 0]
> * [1, 2]
> 
> The denominator for each loss consists of the positive pair and all negative pairs for that positive pair. So the positive pair [0, 2] is not included at all in the loss for [0, 1].

Got it! So it seems like the denominator for each loss term is the negative pairs against that row - is that accurate to say?

In case there are a different number of positive pairs against each image, would that mean that the denominator would have a different number of terms for each positive pair?

**Comment by KevinMusgrave** [comment]
> Got it! So it seems like the denominator for each loss term is the negative pairs against that row - is that accurate to say?

Yes

> In case there are a different number of positive pairs against each image, would that mean that the denominator would have a different number of terms for each positive pair?

Yes, the number of terms in the denominator depends on how many relevant negative pairs there are for a particular positive pair.

**Comment by dhruvbird** [comment]
> Yes, the number of terms in the denominator depends on how many negative pairs have the same "anchor" as the current positive pair. For an explanation of "anchor", see the `"How exactly is the NTXentLoss computed?"` section here: https://kevinmusgrave.github.io/pytorch-metric-learning/losses/#ntxentloss

Ah! This is super useful - I believe I incorrectly assumed initially that the number of negative pairs (terms making up the denominator) were the same irrespective of how many positive pairs exist. I think this makes sense and the loss itself seems sound in the case of a different number of positive pairs per sample.

That said, if one has 100 input images and 2 positive pairs per image (instead of just 1 positive pair), I guess this would increase the number of loss terms one needs to compute by a factor of 2x. However, I think that the way the terms are structured, one could just re-use the denominator term (and I'm assuming that it is reused) for all the loss terms originating from the positive pairs that have the same LHS component, so efficiency isn't a problem.

**Comment by KevinMusgrave** [comment]
> I think that the way the terms are structured, one could just re-use the denominator term (and I'm assuming that it is reused)

The negative pairs for each positive pair are found through this vectorized operation:

https://github.com/KevinMusgrave/pytorch-metric-learning/blob/8e843863d00014c1b5294a1dd1c245118b74e1dc/src/pytorch_metric_learning/losses/ntxent_loss.py#L26-L28

I'm not sure if it's the most efficient approach though.
