### ISSUE TITLE
What c_f.process_label actually does?

### ISSUE THREAD

**Issue by brianw0924** [KevinMusgrave/pytorch-metric-learning#624]
Hi, I'm modifying the code to customize to my scenario

I'm wondering what c_f.process_label actually does? Can I skip it? Is there any warning?

Thank you.

**Comment by KevinMusgrave** [comment]
Here's the code:
https://github.com/KevinMusgrave/pytorch-metric-learning/blob/c57ebdddcbe2bf7e79e331779b65f97a81491513/src/pytorch_metric_learning/utils/common_functions.py#L90-L94

First it changes labels so that they start from 0, but only if you set `set_min_label_to_zero` to True.
Next it selects a particular hierarchy level (column) of the labels, if your `labels` array is 2-dimensional.
Then it converts the labels to a torch tensor, if it's not already a torch tensor.

**Comment by brianw0924** [comment]
Thank you. Got it!
